### PR TITLE
US05_Alison

### PR DESCRIPTION
**Pull request by alisonh7574**

### CODE REVIEW

**Review by Oneiljr1 — APPROVED** [review]
Great Job

**Review by bbflorent — APPROVED** [review]
great job

**Review by bbflorent — CHANGES_REQUESTED** [review]
can you please run your code again.there is a issue on my side

**Review by Saharnaz1 — CHANGES_REQUESTED** [review]
Stale element with one of the locators, but it should work after that. Keep up the good work!

**Review by PuujeeS — APPROVED** [review]
Looks great.

**Review by bbflorent — APPROVED** [review]
perfect

**Review by Saharnaz1 — APPROVED** [review]
Great job --- NOTE TO EVERYONE: ALVIN AND ADAM CORRECTED THE CODE PLEASE DO NOT TOUCH IT

**Pull request merged**
